### PR TITLE
Formula SAE Electric 2024 Fixes and Features

### LINKED ISSUE #27: AIRs/Precharge Edge Case
This task is to fix an edge case on the ACU that we tried to fix with the fix described below:

"this was to fix a bug if precharge failed, the car state wouldn't be set to "TSA" so the open airs routine wouldn't actually open the airs, so the negative air and precharge relay would be closed while idle.. yikes. can be rewritten to be better after giving it some thought"

**Here is where you have to look for the error:**
- in the go_tsa function we set the TSA state and if we don't reach that set_car_state call we are in the else and call go_idle
- in the go_idle function we check the air_state but technically the car state wouldn't have changed and because the - go_idle function checks for (get_car_state() != IDLE) then we won't actually release the AIRs
negative AIR would be stuck closed

We need to fix this before merging codeSprint into main!

Here's the commit hash so you can see what needs to be changed: cd673df561b52b32ea5b8a34ffdb1c606f64908c

### PR DESCRIPTION
**Pull request by Sedkian**
This Pull Request introduces fixes and features that were added in the days right before and during the Formula SAE Electric 2024 Competition.

### CODE REVIEW

File: Core/Inc/main.h
Comment (Mason-Pronger) [inline Core/Inc/main.h:1]: Should this not be left on for the release version of the ACU?

File: Core/Src/main.c
Comment (Mason-Pronger) [inline Core/Src/main.c:1]: Is this delay necessary?

File: Core/Src/acb_startup.c [hunk 1]
```diff
@@ -146,10 +147,12 @@ void go_idle(){
 			 log_and_handle_error(ERROR_AIR_WELD, &air_weld_handler);
 		}
 
-		cooling_disable_pump();
-		cooling_disable_rad_fans();
+		//cooling_disable_pump();
+		//cooling_disable_rad_fans();
```
Comment (Mason-Pronger) [inline Core/Src/acb_startup.c:151]: Might want to get rid of these comments or lines.

**Review by Mason-Pronger — COMMENTED** [review]
Overall looks good to me. I've made a few comments suggesting you remove some unnecessary lines of code. 👍

**Comment by CPollreis** [comment]
@Mason-Pronger Can this be merged in? Most of these comments are addressable by tests/checks on the bench. I want to re-read my document and clean up the dead code on the controller boards, bad comments etc.

going to branch off codeSprint for the time being

**Review by Mason-Pronger — APPROVED** [review]
LGTM
